name: macos_image.yml
on:
  - workflow_dispatch
  - workflow_call
jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '25'
          cache: 'gradle'

      - name: Build Jlink native image
        run: ./gradlew jpackageImage

      - name: Archive .app bundle
        run: |
            cd build/jpackage
            ditto -c -k --sequesterRsrc --keepParent MP3Reorder.app MP3Reorder-macOS.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: MP3Reorder-macOS
          path: build/jpackage/MP3Reorder-macOS.zip
          if-no-files-found: error